version: '3.3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    command: >
      sh -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      (echo \"from django.contrib.auth import get_user_model; \
      User = get_user_model(); \
      User.objects.filter(username='$DJANGO_SUPERUSER_USERNAME').exists() or \
      User.objects.create_superuser(\
      '$DJANGO_SUPERUSER_USERNAME', '$DJANGO_SUPERUSER_EMAIL', \
      '$DJANGO_SUPERUSER_PASSWORD')\" | python3 manage.py shell) &&
      python3 manage.py runserver 0.0.0.0:8000"
